core/urls.py
from django.urls import path
from . import views
from core.views import HomeView, AboutView, ContactView

app_name = "core"

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about', AboutView.as_view(), name='about'),
    path('contact', ContactView.as_view(), name='contact'),
]

imgman/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('sinimg/', include("sinimg.urls")),
    path('steg/', include("steg.urls")),
    path('', RedirectView.as_view(url='core/'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sinimg/urls.py
from django.urls import path, include
from . import views
from django.views.generic import RedirectView
from sinimg.views import Upload, ProcessImage, SelectChoice

app_name = 'sinimg'

urlpatterns = [
    path('', RedirectView.as_view(url='core/', permanent=True)),
    path('core/', include('core.urls')),
    path("upload/", Upload.as_view(), name='upload'),
    path("select_choice/", SelectChoice.as_view(), name="select-choice"),
    path("process/<int:choice>/", ProcessImage.as_view(), name="process"),
]

steg/urls.py
from django.urls import path, include
from . import views
from django.views.generic import RedirectView
from steg.views import Upload, ProcessImage, SelectChoice

app_name = 'steg'

urlpatterns = [
    path('', RedirectView.as_view(url='core/', permanent=True)),
    path('core/', include('core.urls')),
    path("upload/", Upload.as_view(), name='upload'),
    path("select_choice/", SelectChoice.as_view(), name="select-choice"),
    path("process/<int:choice>/", ProcessImage.as_view(), name="process"),
]

templates/about.html
{% extends 'base.html' %}
{% block body %}
<div class="row about-section full-width">
    <div class="flex-child">
        <h1>About PixelCraft</h1>
        <p class="text">
            PixelCraft is a unique web app which provides a myriad of image manipulation options
            such as image blurring, black and white filters, converting to pdf, adding
            grayscale effect, and resizing the image. It's built with Django, a Python web framework.
        </p>
    </div>
    <div class="flex-child">
        <img class="flex-child__img" src="../static/images/pic.jpg" alt="">
    </div>
</div>
<div class="about-section__mission">
    <div class="inner-container">
        <h1>Our Mission</h1>
        <p class="main">Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio reiciendis dolorum
            repellendus sint atque sed et quas eveniet pariatur aspernatur dolor nisi aperiam,
            reprehenderit quae veniam. Cum praesentium molestiae doloremque.
        </p>
    </div>

</div>
    <div class="row">
        <div class="col-xs-4">
            <h4>23K</h4>
            <h3>Images</h3>
            <p>Processed this year</p>
        </div>
        <div class="col-xs-4">
            <h4>195</h4>
            <h3>Countries</h3>
            <p>Our website is used all over the world</p>
        </div>
        <div class="col-xs-4">
            <h4>23K</h4>
            <h3>Images</h3>
            <p>Processed this year</p>
        </div>
    </div>
</div>
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html5>
    
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'css/global.css' %}">
        <link rel="stylesheet" href="{% static 'css/utils.css' %}">
        <link rel="stylesheet" href="{% static 'css/container.css' %}">
        <link rel="stylesheet" href="{% static 'css/button.css' %}">
        <link rel="stylesheet" href="{% static 'css/input.css' %}">
        <link rel="stylesheet" href="{% static 'css/footer.css' %}">
        <link rel="stylesheet" href="{% static 'css/contact.css' %}">
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
        <link rel="stylesheet" href="{% static 'css/forms.css' %}">
        <link rel="stylesheet" href="{% static 'css/images.css' %}">
        <link rel="stylesheet" href="{% static 'css/about.css' %}">
        <link rel="stylesheet" href="{% static 'css/media-query.css' %}">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/fd1fb5a56f.js" crossorigin="anonymous"></script>
        
r

        <title>{% block title %}{% endblock title %}</title>
    </head>

    <body>
        <div id="app">
            <nav>
                <a class="burger-nav"></a>
                <ul class="navbar__list">
                    <li class="navbar__list--item">
                        <a class="active" href="{% url 'core:index' %}"><i class="glyphicon glyphicon-home"> </i> Home
                            Page</a>
                    </li>
                    {% comment %} <li class="navbar__list--item">
                        <a class="active" href="{% url 'sinimg:upload' %}"><i class="glyphicon glyphicon-upload"> </i>
                            Image Processing</a>
                    </li> {% endcomment %}

                    <li class="navbar__list--item">
                        <a class="active" href="{% url 'sinimg:upload' %}"><i
                                class="glyphicon glyphicon-refresh"></i>Image
                            Processing</a>
                    </li>
                    <li class="navbar__list--item">
                        <a class="active" href="{% url 'steg:upload' %}"><i class="glyphicon glyphicon-upload"> </i>
                            Steganography</a>
                    </li>
                    <li class="navbar__list--item">
                        <a class="active" href="{% url 'core:about' %}"><i
                                class="glyphicon glyphicon-info-sign"></i>About
                            us</a>
                    </li>
                    <li class="navbar__list--item">
                        <a class="active" href="{% url 'core:contact' %}"><i
                                class="glyphicon glyphicon-user"></i>Contact
                            us</a>
                    </li>
                </ul>
            </nav>
            {% if messages %} {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %} {% endif %}
            <div class="container-fluid">{% block body %}{% endblock body %}</div>
            <footer class="footer">

                <div class="d-flex">
                    <p class="text-white">© PixelCraft</p>
                </div>

            </footer>
        </div>
    </body>

    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/menu.js' %}"></script>
    <script src="{% static 'js/upload.js' %}"></script>
    <script>
        $('.prevent').on('click', function (e) {
            if ($(".default_input").val() == "") {
                alert("Pls enter a secret key");
                e.preventDefault();
            }
        })
    </script>
</html5>

templates/contact.html
{% extends 'base.html' %} {% block body %}
<div class="main">
  <form method="post" class="contact-form">
    {% csrf_token %}
    <h1 class="contact-form__title">Contact Form</h1>
    <div class="contact-form__input_group">
      <div class="input-group">
        <input type="text" class="contact-form__input" name="name" placeholder="Full name" />
      </div>
      <div class="input-group">
        <input type="email" class="contact-form__input" name="email" placeholder="E-mail" />
      </div>
      <div class="input-group">
        <textarea class="contact-form__input" name="message" placeholder="How can we help?"
          style="height: 100PX"></textarea>
      </div>
    </div>
    <input class="contact-form__button" type="submit" value="Send" />
  </form>
  <footer class="bg-dark text-white pt-5 pb-4"></footer>
  <div class="follow-widget">
    <h2>Follow Us</h2>
    <p>Stay updated via social media</p>
    <ul>
      
      <li><a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
      
      <li><a href=""><i class="fa fa-github" aria-hidden="true"></i></a></li>
      
    </ul>
  </div>
</div>
{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}
{% block body %}
<div class="container home-section">
    <div class="container-fluid home-section--flex-column">
        <div>
            {% load static %}
            <img src="{% static 'images/logo.png' %}" alt="imgman-logo">
        </div>

        <div>
            <p class="home-section__content">PixelCraft is a unique web app which provides myriad of image manipulation
                options like
                blurring of
                image, black and white filters, converting to pdf, adding grayscale effect, resizing the image. It's
                built with django, a python web framework.</p>
        </div>
    </div>

    <div class="images">
        <p class="images__title">Uploaded Base Image:</p>
        <img class="images__image" src="{% static 'images/img-manipulation/base-img.jpg' %}" alt="base-image">
        <div>
            <p class="images__title">Results: </p>
            <img class="images__image--result" src="{% static 'images/img-manipulation/gray.png' %}" alt="gray-image">
            <img class="images__image--result" src="{% static 'images/img-manipulation/blur.png' %}" alt="blur-image">
            <img class="images__image--result" src="{% static 'images/img-manipulation/black.png' %}" alt="black-image">
            <img class="images__image--result" src="{% static 'images/img-manipulation/tint.png' %}" alt="tint-image">
        </div>
    </div>

</div>
{% endblock body %}